version: "3.9"
services: 
  Alpine:
    image: apache-test:alpine
    command: /sbin/init
    expose:
      - 80
      - 443
    ports:
    - "80:80"
    - "443:443"
    build:
      context: .
      args:
        IMAGE_BASE: ALPINE
        IMAGE: alpine:3.15
  CentOS7:
    image: apache-test:centos7
    command: /usr/sbin/init
    expose:
      - 80
      - 443
    ports:
    - "80:80"
    - "443:443"
    build:
      context: .
      args:
        IMAGE_BASE: CENTOS7
        IMAGE: centos:7
  CentOS8:
    image: apache-test:centos8
    command: /usr/sbin/init
    expose:
      - 80
      - 443
    ports:
    - "80:80"
    - "443:443"
    build:
      context: .
      args:
        IMAGE_BASE: CENTOS8
        IMAGE: centos:8
  RockyLinux:
    image: apache-test:rockylinux
    command: /usr/sbin/init
    expose:
      - 80
      - 443
    ports:
    - "80:80"
    - "443:443"
    build:
      context: .
      args:
        IMAGE_BASE: ROCKYLINUX
        IMAGE: rockylinux:8.5